import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Unolingo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex justify-center items-center h-screen w-screen bg-[#58cc02]">
                <div className="wrapper bg-gray-100 w-3/5 h-4/5 rounded-xl p-10 shadow-xl">
                    <h2 className="text-3xl font-medium">Write this in English</h2>
                    <div className="question-wrapper mt-10 flex gap-2 text-lg">
                        <div className="word underline underline-offset-8 decoration-dotted decoration-gray-600">Lol</div>
                        <div className="word underline underline-offset-8 decoration-dotted decoration-gray-600">Lol</div>
                        <div className="word underline underline-offset-8 decoration-dotted decoration-gray-600">Lol</div>
                        <div className="word underline underline-offset-8 decoration-dotted decoration-gray-600">Lol</div>
                        
                    </div>
                    <div className="answer-wrapper mt-10">
                        <div className="answers flex gap-2 w-full ">
                            <div className="word bg-white shadow-lg py-2 px-4 rounded-lg">lollol</div>
                            <div className="word bg-white shadow-lg py-2 px-4 rounded-lg">lololol</div>
                            <div className="word bg-white shadow-lg py-2 px-4 rounded-lg">llolo</div>
                            <div className="word bg-white shadow-lg py-2 px-4 rounded-lg">lololo</div>
                        </div>
                        <hr className=" border-gray-300"/>
                        <br />
                        <hr className="mt-5 border-gray-300"/>
                    </div>

                    <div className="option-wrapper mt-16 flex gap-2">
                        <div className="option bg-white shadow-lg py-2 px-4 rounded-lg">Lol</div>
                        <div className="option bg-white shadow-lg py-2 px-4 rounded-lg">Lol</div>
                        <div className="option bg-white shadow-lg py-2 px-4 rounded-lg">Lol</div>
                        <div className="option bg-white shadow-lg py-2 px-4 rounded-lg">Lol</div>
                        <div className="option bg-white shadow-lg py-2 px-4 rounded-lg">Lol</div>
                        <div className="option bg-white shadow-lg py-2 px-4 rounded-lg">Lol</div>
                        <div className="option bg-white shadow-lg py-2 px-4 rounded-lg">Lol</div>
                    </div>
                    <div className="flex justify-center mt-28">
                    <button
                      className="bg-[#58cc02] hover:bg-[#448d0d] transition-all text-white font-medium text-lg px-10 py-2  rounded-lg shadow-lg "
                    >Check Your Answer</button>
                    </div>
                </div>
            </main>
        </div>
    );
}
